<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BangDiemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('bang_diems')->delete();

        DB::table('bang_diems')->truncate();

        DB::table('bang_diems')->insert([
            [
                'ma_mon'        =>  'CS 211',
                'ten_mon'       =>  'Lập Trình Cơ Sở',
                'diem_so'       =>  8.8,
                'diem_chu'      =>  'A',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  1,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'IS 301',
                'ten_mon'       =>  'Cơ Sở Dữ Liệu',
                'diem_so'       =>  8.4,
                'diem_chu'      =>  'A-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  1,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 311',
                'ten_mon'       =>  'Lập Trình Hướng Đối Tượng',
                'diem_so'       =>  6.7,
                'diem_chu'      =>  'B-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  1,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CR 424',
                'ten_mon'       =>  'Lập Trình Ứng Dụng cho các Thiết Bị Di Động',
                'diem_so'       =>  5.9,
                'diem_chu'      =>  'C',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  1,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 252',
                'ten_mon'       =>  'Mạng Máy Tính',
                'diem_so'       =>  6.3,
                'diem_chu'      =>  'C+',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  1,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 303',
                'ten_mon'       =>  'Phân Tích & Thiết Kế Hệ Thống',
                'diem_so'       =>  6,
                'diem_chu'      =>  'C+',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  1,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'IS 401',
                'ten_mon'       =>  'Hệ Quản Trị Cơ Sở Dữ Liệu',
                'diem_so'       =>  6.2,
                'diem_chu'      =>  'C+',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  1,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 316',
                'ten_mon'       =>  'Giới Thiệu Cấu Trúc Dữ Liệu & Giải Thuật',
                'diem_so'       =>  6.4,
                'diem_chu'      =>  'C+',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  1,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 353',
                'ten_mon'       =>  'Phân Tích Thiết Kế Hướng Đối Tượng',
                'diem_so'       =>  7.8,
                'diem_chu'      =>  'B+',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  1,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 417',
                'ten_mon'       =>  'Trí Tuệ Nhân Tạo (Biểu Diễn & Giải Thuật)',
                'diem_so'       =>  7.7,
                'diem_chu'      =>  'B+',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  1,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 420',
                'ten_mon'       =>  'Hệ Phân Tán (J2EE, .NET)',
                'diem_so'       =>  8.8,
                'diem_chu'      =>  'A',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  1,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 462',
                'ten_mon'       =>  'Kiểm Thử & Đảm Bảo Chất Lượng Phần Mềm',
                'diem_so'       =>  6.8,
                'diem_chu'      =>  'B-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  1,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 464',
                'ten_mon'       =>  'Lập Trình Ứng Dụng .NET',
                'diem_so'       =>  9.4,
                'diem_chu'      =>  'A',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  1,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 403',
                'ten_mon'       =>  'Công Nghệ Phần Mềm',
                'diem_so'       =>  '8.2',
                'diem_chu'      =>  'A-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  1,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 445',
                'ten_mon'       =>  'Đồ Án Chuyên Ngành: Tích Hợp Hệ Thống (COTS)',
                'diem_so'       =>  8.6,
                'diem_chu'      =>  'A',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  1,
                'is_duyet'      =>  1,
            ],
            //2
            [
                'ma_mon'        =>  'CS 211',
                'ten_mon'       =>  'Lập Trình Cơ Sở',
                'diem_so'       =>  9.2,
                'diem_chu'      =>  'A',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  2,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'IS 301',
                'ten_mon'       =>  'Cơ Sở Dữ Liệu',
                'diem_so'       =>  8.8,
                'diem_chu'      =>  'A',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  2,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 311',
                'ten_mon'       =>  'Lập Trình Hướng Đối Tượng',
                'diem_so'       =>  6.9,
                'diem_chu'      =>  'B-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  2,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CR 424',
                'ten_mon'       =>  'Lập Trình Ứng Dụng cho các Thiết Bị Di Động',
                'diem_so'       =>  7,
                'diem_chu'      =>  'B',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  2,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 252',
                'ten_mon'       =>  'Mạng Máy Tính',
                'diem_so'       =>  6,
                'diem_chu'      =>  'C+',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  2,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 303',
                'ten_mon'       =>  'Phân Tích & Thiết Kế Hệ Thống',
                'diem_so'       =>  7.1,
                'diem_chu'      =>  'B',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  2,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'IS 401',
                'ten_mon'       =>  'Hệ Quản Trị Cơ Sở Dữ Liệu',
                'diem_so'       =>  7.2,
                'diem_chu'      =>  'B',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  2,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 316',
                'ten_mon'       =>  'Giới Thiệu Cấu Trúc Dữ Liệu & Giải Thuật',
                'diem_so'       =>  6.1,
                'diem_chu'      =>  'C+',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  2,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 353',
                'ten_mon'       =>  'Phân Tích Thiết Kế Hướng Đối Tượng',
                'diem_so'       =>  8.9,
                'diem_chu'      =>  'A',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  2,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 417',
                'ten_mon'       =>  'Trí Tuệ Nhân Tạo (Biểu Diễn & Giải Thuật)',
                'diem_so'       =>  8,
                'diem_chu'      =>  'A-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  2,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 420',
                'ten_mon'       =>  'Hệ Phân Tán (J2EE, .NET)',
                'diem_so'       =>  8.8,
                'diem_chu'      =>  'A',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  2,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 462',
                'ten_mon'       =>  'Kiểm Thử & Đảm Bảo Chất Lượng Phần Mềm',
                'diem_so'       =>  6.5,
                'diem_chu'      =>  'B-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  2,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 464',
                'ten_mon'       =>  'Lập Trình Ứng Dụng .NET',
                'diem_so'       =>  9.4,
                'diem_chu'      =>  'A',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  2,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 403',
                'ten_mon'       =>  'Công Nghệ Phần Mềm',
                'diem_so'       =>  '9',
                'diem_chu'      =>  'A',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  2,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 445',
                'ten_mon'       =>  'Đồ Án Chuyên Ngành: Tích Hợp Hệ Thống (COTS)',
                'diem_so'       =>  8.7,
                'diem_chu'      =>  'A',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  2,
                'is_duyet'      =>  1,
            ],
            //3
            [
                'ma_mon'        =>  'CS 211',
                'ten_mon'       =>  'Lập Trình Cơ Sở',
                'diem_so'       =>  7.6,
                'diem_chu'      =>  'B+',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  3,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'IS 301',
                'ten_mon'       =>  'Cơ Sở Dữ Liệu',
                'diem_so'       =>  6.3,
                'diem_chu'      =>  'C+',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  3,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 311',
                'ten_mon'       =>  'Lập Trình Hướng Đối Tượng',
                'diem_so'       =>  5,
                'diem_chu'      =>  'C-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  3,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CR 424',
                'ten_mon'       =>  'Lập Trình Ứng Dụng cho các Thiết Bị Di Động',
                'diem_so'       =>  5,
                'diem_chu'      =>  'C-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  3,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 252',
                'ten_mon'       =>  'Mạng Máy Tính',
                'diem_so'       =>  6.3,
                'diem_chu'      =>  'C+',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  3,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 303',
                'ten_mon'       =>  'Phân Tích & Thiết Kế Hệ Thống',
                'diem_so'       =>  5.2,
                'diem_chu'      =>  'C-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  3,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'IS 401',
                'ten_mon'       =>  'Hệ Quản Trị Cơ Sở Dữ Liệu',
                'diem_so'       =>  5.5,
                'diem_chu'      =>  'C',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  3,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 316',
                'ten_mon'       =>  'Giới Thiệu Cấu Trúc Dữ Liệu & Giải Thuật',
                'diem_so'       =>  4.8,
                'diem_chu'      =>  'C-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  3,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 353',
                'ten_mon'       =>  'Phân Tích Thiết Kế Hướng Đối Tượng',
                'diem_so'       =>  7.2,
                'diem_chu'      =>  'B',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  3,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 417',
                'ten_mon'       =>  'Trí Tuệ Nhân Tạo (Biểu Diễn & Giải Thuật)',
                'diem_so'       =>  8,
                'diem_chu'      =>  'A-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  3,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 420',
                'ten_mon'       =>  'Hệ Phân Tán (J2EE, .NET)',
                'diem_so'       =>  8.2,
                'diem_chu'      =>  'A-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  3,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 462',
                'ten_mon'       =>  'Kiểm Thử & Đảm Bảo Chất Lượng Phần Mềm',
                'diem_so'       =>  7.2,
                'diem_chu'      =>  'B',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  3,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 464',
                'ten_mon'       =>  'Lập Trình Ứng Dụng .NET',
                'diem_so'       =>  7.8,
                'diem_chu'      =>  'B+',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  3,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 403',
                'ten_mon'       =>  'Công Nghệ Phần Mềm',
                'diem_so'       =>  '8.6',
                'diem_chu'      =>  'A',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  3,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 445',
                'ten_mon'       =>  'Đồ Án Chuyên Ngành: Tích Hợp Hệ Thống (COTS)',
                'diem_so'       =>  8.3,
                'diem_chu'      =>  'A-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  3,
                'is_duyet'      =>  1,
            ],
            //4
            [
                'ma_mon'        =>  'CS 211',
                'ten_mon'       =>  'Lập Trình Cơ Sở',
                'diem_so'       =>  9.6,
                'diem_chu'      =>  'A+ ',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  4,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'IS 301',
                'ten_mon'       =>  'Cơ Sở Dữ Liệu',
                'diem_so'       =>  8.6,
                'diem_chu'      =>  'A',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  4,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 311',
                'ten_mon'       =>  'Lập Trình Hướng Đối Tượng',
                'diem_so'       =>  8.7,
                'diem_chu'      =>  'A',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  4,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CR 424',
                'ten_mon'       =>  'Lập Trình Ứng Dụng cho các Thiết Bị Di Động',
                'diem_so'       =>  9.3,
                'diem_chu'      =>  'A',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  4,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 252',
                'ten_mon'       =>  'Mạng Máy Tính',
                'diem_so'       =>  6.6,
                'diem_chu'      =>  'B-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  4,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 303',
                'ten_mon'       =>  'Phân Tích & Thiết Kế Hệ Thống',
                'diem_so'       =>  7.2,
                'diem_chu'      =>  'B',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  4,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'IS 401',
                'ten_mon'       =>  'Hệ Quản Trị Cơ Sở Dữ Liệu',
                'diem_so'       =>  7.7,
                'diem_chu'      =>  'B+',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  4,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 316',
                'ten_mon'       =>  'Giới Thiệu Cấu Trúc Dữ Liệu & Giải Thuật',
                'diem_so'       =>  8.2,
                'diem_chu'      =>  'B',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  4,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 353',
                'ten_mon'       =>  'Phân Tích Thiết Kế Hướng Đối Tượng',
                'diem_so'       =>  8.9,
                'diem_chu'      =>  'A',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  4,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 417',
                'ten_mon'       =>  'Trí Tuệ Nhân Tạo (Biểu Diễn & Giải Thuật)',
                'diem_so'       =>  6.9,
                'diem_chu'      =>  'B-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  4,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 420',
                'ten_mon'       =>  'Hệ Phân Tán (J2EE, .NET)',
                'diem_so'       =>  8.6,
                'diem_chu'      =>  'A',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  4,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 462',
                'ten_mon'       =>  'Kiểm Thử & Đảm Bảo Chất Lượng Phần Mềm',
                'diem_so'       =>  7.7,
                'diem_chu'      =>  'B+',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  4,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 464',
                'ten_mon'       =>  'Lập Trình Ứng Dụng .NET',
                'diem_so'       =>  9.3,
                'diem_chu'      =>  'A',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  4,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 403',
                'ten_mon'       =>  'Công Nghệ Phần Mềm',
                'diem_so'       =>  '8.2',
                'diem_chu'      =>  'A-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  4,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 445',
                'ten_mon'       =>  'Đồ Án Chuyên Ngành: Tích Hợp Hệ Thống (COTS)',
                'diem_so'       =>  8.3,
                'diem_chu'      =>  'A-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  4,
                'is_duyet'      =>  1,
            ],
            //5
            [
                'ma_mon'        =>  'CS 211',
                'ten_mon'       =>  'Lập Trình Cơ Sở',
                'diem_so'       =>  9.4,
                'diem_chu'      =>  'A+',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  5,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'IS 301',
                'ten_mon'       =>  'Cơ Sở Dữ Liệu',
                'diem_so'       =>  8.5,
                'diem_chu'      =>  'A',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  5,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 311',
                'ten_mon'       =>  'Lập Trình Hướng Đối Tượng',
                'diem_so'       =>  8.1,
                'diem_chu'      =>  'A-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  5,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CR 424',
                'ten_mon'       =>  'Lập Trình Ứng Dụng cho các Thiết Bị Di Động',
                'diem_so'       =>  6.8,
                'diem_chu'      =>  'B-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  5,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 252',
                'ten_mon'       =>  'Mạng Máy Tính',
                'diem_so'       =>  5.8,
                'diem_chu'      =>  'C',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  5,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 303',
                'ten_mon'       =>  'Phân Tích & Thiết Kế Hệ Thống',
                'diem_so'       =>  7,
                'diem_chu'      =>  'B',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  5,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'IS 401',
                'ten_mon'       =>  'Hệ Quản Trị Cơ Sở Dữ Liệu',
                'diem_so'       =>  7,
                'diem_chu'      =>  'B',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  5,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 316',
                'ten_mon'       =>  'Giới Thiệu Cấu Trúc Dữ Liệu & Giải Thuật',
                'diem_so'       =>  5.9,
                'diem_chu'      =>  'C  ',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  5,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 353',
                'ten_mon'       =>  'Phân Tích Thiết Kế Hướng Đối Tượng',
                'diem_so'       =>  8.6,
                'diem_chu'      =>  'A',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  5,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 417',
                'ten_mon'       =>  'Trí Tuệ Nhân Tạo (Biểu Diễn & Giải Thuật)',
                'diem_so'       =>  8.2,
                'diem_chu'      =>  'A-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  5,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 420',
                'ten_mon'       =>  'Hệ Phân Tán (J2EE, .NET)',
                'diem_so'       =>  8.7,
                'diem_chu'      =>  'A',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  5,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 462',
                'ten_mon'       =>  'Kiểm Thử & Đảm Bảo Chất Lượng Phần Mềm',
                'diem_so'       =>  6.4,
                'diem_chu'      =>  'C+',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  5,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 464',
                'ten_mon'       =>  'Lập Trình Ứng Dụng .NET',
                'diem_so'       =>  9.4,
                'diem_chu'      =>  'C',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  5,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 403',
                'ten_mon'       =>  'Công Nghệ Phần Mềm',
                'diem_so'       =>  '8.4',
                'diem_chu'      =>  'A-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  5,
                'is_duyet'      =>  1,
            ],
            [
                'ma_mon'        =>  'CS 445',
                'ten_mon'       =>  'Đồ Án Chuyên Ngành: Tích Hợp Hệ Thống (COTS)',
                'diem_so'       =>  8.3,
                'diem_chu'      =>  'A-',
                'hinh_anh'      =>  '',
                'id_sinh_vien'  =>  5,
                'is_duyet'      =>  1,
            ],
        ]);
    }
}
